### ISSUE TITLE
adding deblock back

### ISSUE THREAD

**Issue by realfinder** [Asd-g/MPEG2DecPlus#1]
hi
can you add back deblock with HBD update from https://github.com/mysteryx93/Avisynth-Deblock to MPEG2DecPlus? I can have both but avs+ don't like many plugins in autoload and deblock always come with DGDecode and MPEG2Source and any mod like MPEG2DecPlus keep this behavior

**Comment by Asd-g** [comment]
Hi,
I wouldn't add it back.
Yes, the original version and any mod come with already old Deblock. I think there is no a reason to include the new version because it's already a standalone plugin.

**Comment by realfinder** [comment]
deblock was a standalone plugin since the beginning but it also included in MPEG2Dec

**Comment by Asd-g** [comment]
Sorry, I still don't see a reason to include a standalone filter here.
