### ISSUE TITLE
D2VSource runs faster in single threaded mode

### ISSUE THREAD

**Issue by DonCanjas** [Asd-g/MPEG2DecPlus#11]
I did an FPS analysis with and without Prefetch() only to spot a huge difference in performance. I have an 6 core cpu.
My script:
```
D2VSource("H:\Coisas\Anime\Raw\Monster\Demux\monster-001_Video01.ENG.d2v")
#Prefetch(6)
```

No Prefetch() -> Prefetch(6)
<img src=https://cdn.discordapp.com/attachments/933020232660975676/983328267987714108/AvsPmod_M0l6MkQcuR.png /> <img src=https://cdn.discordapp.com/attachments/933020232660975676/983328353765429288/unknown.png />

**Comment by Asd-g** [comment]
Source filters are always MT_SERIALIZED (do not use prefetch() for them). There is info [here](http://avisynth.nl/index.php/AviSynth%2B#Multithreading_.28MT.29_Notes).
