### ISSUE TITLE
changing function name

### ISSUE THREAD

**Issue by realfinder** [Asd-g/MPEG2DecPlus#2]
since this plugin already has so many changes, isn't better to make it MPEG2DecPlus? and remove all     disabled parameters

**Comment by Asd-g** [comment]
Yes, it's probably better. LumaYUV could be removed too...

**Comment by realfinder** [comment]
I don't use it, so yes, then it become pure MPEG2Dec

**Comment by realfinder** [comment]
and maybe it better to move LumaYUV and BlindPP to DeBlock plugin

**Comment by realfinder** [comment]
and btw, I think it should be named as MPEG2DecLite, since Plus mean with more things and that not true since it less that older one (even old MPEG2DecPlus is less than original one)

maybe MiniMPEG2Dec not MPEG2DecLite

**Comment by Asd-g** [comment]
I made quick test and ColorYUV() is faster than LumaYUV() (both identical output).
Is BlindPP useful nowadays?

**Comment by realfinder** [comment]
it used in some scripts like http://www.avisynth.nl/index.php/FunkyDeBlock

I think it's more or less useful as deblock plugin so it should be in it (deblock plugin)

**Comment by realfinder** [comment]
and about the name, I have another suggestion, which is make it d2vsource as VS one (which I think is more suitable)

**Comment by Asd-g** [comment]
I like that d2vsource name.
I would prefer to move BlindPP  to a standalone plugin.

**Comment by realfinder** [comment]
I have no problem with make it a standalone plugin

**Comment by Asd-g** [comment]
I'll not bother with BlindPP.
FunkyDeBlock probably can use deblock and can get high support in addition.

**Comment by realfinder** [comment]
ok, and since the rename is done I will close this
