### ISSUE TITLE
frame properties

### ISSUE THREAD

**Issue by realfinder** [Asd-g/MPEG2DecPlus#4]
Hi

is it possible to support avs+ frame properties in this plugin?

**Comment by Asd-g** [comment]
Hi,
Frame properties for what - for everything that info=1 returns? Some of the info is available from the clip properties (FrameRate(), current_frame, width, height). Do you want frame properties for those things too?

**Comment by realfinder** [comment]
yes or info=3 since "3: Embed hints in 64 bytes of the frame upper left corner." is hack in first place

so then tivtc and others can use Frame properties instead of hints hack

**Comment by Asd-g** [comment]
Please check version 1.1.0.

**Comment by realfinder** [comment]
it's seems work as it should, thanks!
