### ISSUE TITLE
Regression for relative file paths in d2v files

### ISSUE THREAD

**Issue by ravewulf** [Asd-g/MPEG2DecPlus#7]
I recently updated from D2VSource 1.2.0 to D2VSource 1.2.3 and now receive an error message if the d2v file uses relative paths like this
```
DGIndexProjectFile16
1
Test.vob
[...]
```
The error is "D2VSource: canonical: The system cannot find the file specified.: "/Test.vob""

I have tested and confirmed that the issue first appeared with version 1.2.1 and is likely due to the "Added support for path with forward slash (Windows)." changes.

**Comment by Asd-g** [comment]
I guess your script is: `D2VSource("example.d2v")`.

Use: `D2VSource(".\example.d2v")` or `D2VSource("./example.d2v")`.

**Comment by ravewulf** [comment]
I can confirm that works as a workaround, though the change breaks a lot of existing scripts that will need updating. Would it be possible to have this case built into the next release to maintain previous functionality where the "./" or ".\\" at the beginning is optional?

**Comment by Asd-g** [comment]
This should be fixed with 1.2.4.

**Comment by ravewulf** [comment]
Thank you! I can confirm it is fixed. Closing ticket
