### ISSUE TITLE
_FieldBased and progressive

### ISSUE THREAD

**Issue by realfinder** [Asd-g/MPEG2DecPlus#8]
_FieldBased seems never be 0 if the frame is progressive, so since frame properties based on the "info" [](https://github.com/Asd-g/MPEG2DecPlus#parameters)Parameter I think _FieldBased should see if "Progr Frame" is true or not, if it true then _FieldBased should be 0

**Comment by Asd-g** [comment]
Can you share such sample with `Progr Frame` `true` but `_FieldBased` > 0 ?

Edit: Try the attached file.

[D2VSource.zip](https://github.com/Asd-g/MPEG2DecPlus/files/8499299/D2VSource.zip)

**Comment by ghost** [comment]
@Asd-g
Seems to work, I will edit the message later after some more accurate test. Can you also add Progr Frame to frame property? Or is the same with _EncodedFrameTop/_EncodedFrameBottom same frame number + _FieldBased == 0?
Please read here [https://forum.doom9.org/showthread.php?p=1967539#post1967539](url)

**Comment by Asd-g** [comment]
`Progr Frame` is the same as `_FieldBased` - if `Progr Frame` is `true`, `_FieldBased=0`, otherwise `_FieldBased > 0` depending on the field order.

**Comment by realfinder** [comment]
> Edit: Try the attached file.
> 
> [D2VSource.zip](https://github.com/Asd-g/MPEG2DecPlus/files/8499299/D2VSource.zip)

yes that work fine, thanks
